In [4]:
import pandas as pd

In [5]:
rr=pd.read_csv(r"C:\Users\USER\Downloads\sleep_mobile_stress_dataset_15000.csv")
rr

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
0,1,56,Female,Designer,3.26,86,5.31,7.72,3.49,0,35,119,3.57
1,2,46,Female,Teacher,1.85,32,7.36,9.70,3.01,0,16,299,1.91
2,3,32,Female,Designer,3.04,107,4.50,6.38,5.03,0,17,21,6.05
3,4,25,Male,Software Engineer,9.00,36,6.68,5.53,10.00,0,3,220,9.92
4,5,38,Female,Teacher,3.52,56,7.57,6.69,6.71,4,92,167,5.99
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,14996,39,Male,Manager,8.05,45,8.91,4.33,10.00,1,40,259,10.00
14996,14997,22,Female,Student,6.44,80,6.00,5.22,10.00,2,41,231,7.54
14997,14998,51,Female,Software Engineer,7.01,78,7.27,5.37,8.66,4,93,288,7.78
14998,14999,56,Female,Software Engineer,7.89,6,5.70,5.71,9.56,1,91,47,9.98
14999,15000,20,Female,Freelancer,6.05,93,4.74,5.04,9.33,0,117,64,9.26

In [10]:
rr.head(10)

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
0,1,56,Female,Designer,3.26,86,5.31,7.72,3.49,0,35,119,3.57
1,2,46,Female,Teacher,1.85,32,7.36,9.70,3.01,0,16,299,1.91
2,3,32,Female,Designer,3.04,107,4.50,6.38,5.03,0,17,21,6.05
3,4,25,Male,Software Engineer,9.00,36,6.68,5.53,10.00,0,3,220,9.92
4,5,38,Female,Teacher,3.52,56,7.57,6.69,6.71,4,92,167,5.99
5,6,56,Male,Teacher,7.26,10,7.79,6.16,10.00,2,50,198,7.85
6,7,36,Female,Teacher,4.56,83,6.81,6.81,5.38,0,19,39,5.52
7,8,40,Male,Manager,3.36,89,6.50,8.75,3.48,2,66,127,4.50
8,9,28,Male,Student,2.30,109,7.57,8.05,3.46,3,103,99,2.52
9,10,28,Female,Manager,9.75,46,4.73,5.52,10.00,3,56,121,10.00

In [11]:
rr.tail(10)

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
14990,14991,32,Female,Researcher,5.40,104,5.63,5.93,8.12,1,4,269,6.16
14991,14992,51,Male,Student,7.75,56,6.87,4.91,9.96,2,7,146,9.29
14992,14993,37,Female,Teacher,5.57,30,4.58,6.43,8.28,3,77,44,8.58
14993,14994,54,Male,Designer,5.58,58,8.18,6.72,5.94,0,28,65,6.03
14994,14995,44,Female,Manager,1.57,94,6.60,7.45,3.44,1,92,236,4.63
14995,14996,39,Male,Manager,8.05,45,8.91,4.33,10.00,1,40,259,10.00
14996,14997,22,Female,Student,6.44,80,6.00,5.22,10.00,2,41,231,7.54
14997,14998,51,Female,Software Engineer,7.01,78,7.27,5.37,8.66,4,93,288,7.78
14998,14999,56,Female,Software Engineer,7.89,6,5.70,5.71,9.56,1,91,47,9.98
14999,15000,20,Female,Freelancer,6.05,93,4.74,5.04,9.33,0,117,64,9.26

In [12]:
rr.describe()

,user_id,age,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.00000,15000.000000,15000.000000,15000.000000
mean,7500.500000,38.488467,5.501528,59.708933,6.509683,6.246362,6.980247,1.99880,59.157133,160.890467,6.873009
std,4330.271354,12.007970,2.600085,34.641858,1.452689,1.713644,2.749382,1.41459,34.525705,80.856902,2.730482
min,1.000000,18.000000,1.000000,0.000000,4.000000,1.000000,1.000000,0.00000,0.000000,20.000000,1.000000
25%,3750.750000,28.000000,3.260000,29.000000,5.260000,5.000000,4.750000,1.00000,29.000000,92.000000,4.700000
50%,7500.500000,38.000000,5.490000,60.000000,6.490000,6.250000,7.380000,2.00000,59.000000,162.000000,7.380000
75%,11250.250000,49.000000,7.760000,90.000000,7.790000,7.500000,10.000000,3.00000,89.000000,231.000000,9.450000
max,15000.000000,59.000000,10.000000,119.000000,9.000000,10.000000,10.000000,4.00000,119.000000,299.000000,10.000000

In [13]:
rr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   user_id                           15000 non-null  int64
 1   age                               15000 non-null  int64
 2   gender                            15000 non-null  object
 3   occupation                        15000 non-null  object
 4   daily_screen_time_hours           15000 non-null  float64
 5   phone_usage_before_sleep_minutes  15000 non-null  int64
 6   sleep_duration_hours              15000 non-null  float64
 7   sleep_quality_score               15000 non-null  float64
 8   stress_level                      15000 non-null  float64
 9   caffeine_intake_cups              15000 non-null  int64
 10  physical_activity_minutes         15000 non-null  int64
 11  notifications_received_per_day    15000 non-null  int64
 12  mental_fatigue_score              15000 non-null  float64
dtypes: float64(5), int64(6), object(2)
memory usage: 1.5+ MB

In [15]:
rr.isnull().sum()

user_id                             0
age                                 0
gender                              0
occupation                          0
daily_screen_time_hours             0
phone_usage_before_sleep_minutes    0
sleep_duration_hours                0
sleep_quality_score                 0
stress_level                        0
caffeine_intake_cups                0
physical_activity_minutes           0
notifications_received_per_day      0
mental_fatigue_score                0
dtype: int64

In [20]:
rr['daily_screen_time_hours'].max()

10.0

In [32]:
rr['age'].max()

59

In [33]:
rr['age'].min()

18

In [22]:
rr.sort_values(by='daily_screen_time_hours',ascending=False)

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
14169,14170,59,Male,Researcher,10.0,46,6.59,4.00,10.00,4,57,184,7.69
13995,13996,35,Female,Software Engineer,10.0,18,8.10,5.02,10.00,3,56,25,10.00
919,920,26,Male,Doctor,10.0,74,7.75,3.02,10.00,4,116,204,9.20
2327,2328,38,Female,Manager,10.0,70,6.50,3.11,10.00,2,31,236,10.00
10101,10102,37,Female,Designer,10.0,118,6.46,3.12,10.00,2,39,163,10.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1999,2000,24,Male,Student,1.0,64,7.68,7.96,1.55,0,39,228,1.00
1567,1568,52,Male,Doctor,1.0,59,6.71,7.36,2.86,3,17,88,4.20
5403,5404,49,Male,Student,1.0,18,8.14,8.09,3.03,3,72,120,3.21
7779,7780,39,Female,Freelancer,1.0,25,5.21,7.91,3.10,4,41,177,3.12
9758,9759,43,Male,Doctor,1.0,77,6.21,9.60,1.90,1,15,159,2.62

In [23]:
rr.sort_values(by='daily_screen_time_hours',ascending=True)

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
8179,8180,36,Male,Manager,1.0,76,4.69,6.81,5.02,0,10,192,4.95
1567,1568,52,Male,Doctor,1.0,59,6.71,7.36,2.86,3,17,88,4.20
5403,5404,49,Male,Student,1.0,18,8.14,8.09,3.03,3,72,120,3.21
1999,2000,24,Male,Student,1.0,64,7.68,7.96,1.55,0,39,228,1.00
7779,7780,39,Female,Freelancer,1.0,25,5.21,7.91,3.10,4,41,177,3.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10101,10102,37,Female,Designer,10.0,118,6.46,3.12,10.00,2,39,163,10.00
919,920,26,Male,Doctor,10.0,74,7.75,3.02,10.00,4,116,204,9.20
2327,2328,38,Female,Manager,10.0,70,6.50,3.11,10.00,2,31,236,10.00
13995,13996,35,Female,Software Engineer,10.0,18,8.10,5.02,10.00,3,56,25,10.00
14169,14170,59,Male,Researcher,10.0,46,6.59,4.00,10.00,4,57,184,7.69

In [27]:
rr.sort_values(by='sleep_duration_hours',ascending=False).head(10)

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
4210,4211,49,Male,Designer,2.70,30,9.00,7.66,5.66,1,68,43,4.42
914,915,47,Female,Student,2.80,56,9.00,7.24,4.33,1,52,206,3.19
10142,10143,25,Female,Designer,8.68,41,9.00,5.56,9.67,1,41,257,10.00
8170,8171,57,Male,Freelancer,1.11,12,9.00,8.65,1.31,0,102,256,1.22
12306,12307,34,Female,Designer,4.69,20,9.00,7.58,8.59,4,19,67,9.39
8743,8744,34,Female,Freelancer,7.32,65,9.00,6.14,9.83,1,51,91,8.86
9277,9278,21,Other,Software Engineer,1.48,42,9.00,8.81,1.49,1,69,237,1.00
867,868,23,Female,Designer,4.05,36,9.00,7.66,4.59,4,80,166,5.00
8462,8463,18,Male,Teacher,7.61,13,9.00,6.01,8.73,1,20,153,8.43
4071,4072,36,Female,Student,9.33,41,8.99,3.00,10.00,0,41,79,9.76

In [29]:
rr.sort_values(by='sleep_duration_hours',ascending=True).head(10)

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
4136,4137,20,Male,Designer,1.04,29,4.0,7.94,1.31,4,111,212,1.43
10768,10769,36,Female,Freelancer,4.43,75,4.0,6.39,7.56,3,99,98,5.98
10801,10802,22,Female,Student,2.99,17,4.0,9.85,3.57,4,9,183,3.44
5467,5468,43,Male,Designer,3.49,86,4.0,7.64,4.52,4,80,262,5.24
14164,14165,49,Male,Freelancer,3.82,1,4.0,7.79,4.37,2,45,282,4.41
10240,10241,22,Male,Student,7.92,78,4.0,4.76,8.67,0,70,296,8.35
4659,4660,26,Female,Student,1.69,19,4.0,8.60,1.50,0,77,51,2.27
1684,1685,59,Male,Manager,3.35,36,4.0,8.36,5.90,2,114,151,6.10
14464,14465,44,Female,Designer,3.64,19,4.0,8.50,3.66,1,53,177,4.14
7101,7102,41,Male,Freelancer,4.69,10,4.0,7.81,5.64,2,19,255,5.77

In [30]:
rr.sort_values(by='stress_level',ascending=False).head(10)

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
7500,7501,22,Female,Designer,9.48,25,6.24,2.38,10.0,3,29,138,9.85
8483,8484,45,Female,Designer,8.23,68,7.54,5.61,10.0,4,103,52,8.81
8530,8531,56,Male,Researcher,6.10,56,8.68,5.32,10.0,4,7,190,10.00
8528,8529,43,Female,Teacher,7.89,82,8.18,4.29,10.0,4,54,266,10.00
8526,8527,41,Male,Researcher,8.13,78,5.50,5.52,10.0,1,118,137,10.00
8524,8525,58,Male,Manager,7.91,115,5.75,3.93,10.0,2,16,151,9.29
8523,8524,19,Male,Student,7.23,57,5.93,5.66,10.0,1,59,161,8.91
8521,8522,30,Other,Software Engineer,8.93,77,7.80,3.17,10.0,2,72,268,10.00
3005,3006,55,Male,Student,6.15,81,6.44,5.60,10.0,2,26,151,8.98
8516,8517,38,Male,Designer,9.50,88,8.77,4.50,10.0,0,5,192,10.00

In [31]:
rr.sort_values(by='stress_level',ascending=True).head(10)

,user_id,age,gender,occupation,daily_screen_time_hours,phone_usage_before_sleep_minutes,sleep_duration_hours,sleep_quality_score,stress_level,caffeine_intake_cups,physical_activity_minutes,notifications_received_per_day,mental_fatigue_score
6465,6466,32,Male,Teacher,1.21,58,6.90,9.95,1.0,2,83,228,1.00
3427,3428,36,Female,Freelancer,1.67,46,6.09,8.82,1.0,1,83,262,1.30
9481,9482,56,Male,Manager,1.69,50,6.71,9.91,1.0,1,108,200,1.36
3426,3427,30,Male,Researcher,1.15,28,6.27,9.83,1.0,1,102,77,1.00
12099,12100,45,Female,Freelancer,1.92,64,8.13,9.59,1.0,1,101,202,1.00
6510,6511,43,Female,Doctor,1.22,0,7.07,10.00,1.0,2,29,177,3.14
6514,6515,28,Male,Student,1.23,19,5.34,8.99,1.0,1,22,293,1.00
12110,12111,48,Female,Teacher,1.92,25,4.42,9.78,1.0,4,4,219,1.02
9424,9425,52,Male,Software Engineer,1.44,23,6.66,8.86,1.0,2,86,33,2.48
3408,3409,40,Female,Software Engineer,2.87,10,8.36,10.00,1.0,3,93,21,3.01

In [48]:
len(rr[(rr['age'] < 40) & (rr['daily_screen_time_hours'] > 7)])

2601

In [50]:
len(rr[(rr['age'] > 40) & (rr['daily_screen_time_hours'] > 7)])

2230

In [51]:
len(rr[(rr['age'] > 40) & (rr['stress_level'] > 6)])

4263

In [52]:
len(rr[(rr['age'] < 40) & (rr['stress_level'] > 6)])

4972

In [58]:
rr.groupby('occupation')['daily_screen_time_hours'].count()

occupation
Designer             1813
Doctor               1922
Freelancer           1891
Manager              1962
Researcher           1837
Software Engineer    1917
Student              1861
Teacher              1797
Name: daily_screen_time_hours, dtype: int64

In [59]:
rr.groupby('occupation')['daily_screen_time_hours'].sum()

occupation
Designer              9883.85
Doctor               10556.80
Freelancer           10229.31
Manager              10875.39
Researcher           10021.27
Software Engineer    10640.12
Student              10486.68
Teacher               9829.50
Name: daily_screen_time_hours, dtype: float64

In [60]:
rr.groupby('gender')['daily_screen_time_hours'].sum()

gender
Female    39403.28
Male      39845.07
Other      3274.57
Name: daily_screen_time_hours, dtype: float64

In [61]:
rr.groupby('gender')['stress_level'].sum()

gender
Female    49913.15
Male      50636.67
Other      4153.88
Name: stress_level, dtype: float64

In [63]:
rr.groupby('gender')['mental_fatigue_score'].sum()

gender
Female    49200.76
Male      49864.45
Other      4029.92
Name: mental_fatigue_score, dtype: float64

In [64]:
rr.groupby('gender')['physical_activity_minutes'].sum()

gender
Female    422873
Male      428856
Other      35628
Name: physical_activity_minutes, dtype: int64

In [66]:
rr.groupby('occupation')['caffeine_intake_cups'].sum()

occupation
Designer             3566
Doctor               3875
Freelancer           3886
Manager              3939
Researcher           3708
Software Engineer    3754
Student              3743
Teacher              3511
Name: caffeine_intake_cups, dtype: int64

In [68]:
rr.groupby('age')['stress_level'].mean()

age
18    7.045266
19    6.867667
20    6.744543
21    7.082817
22    7.075089
23    6.948832
24    7.116707
25    7.089008
26    6.833391
27    7.234191
28    7.004199
29    6.763362
30    7.033611
31    6.884262
32    6.814468
33    6.822048
34    7.041030
35    7.174447
36    6.906332
37    7.099086
38    6.886260
39    6.869013
40    6.979922
41    6.735531
42    7.153040
43    7.187345
44    7.051687
45    6.910649
46    7.033443
47    6.963084
48    6.916409
49    6.992697
50    7.118977
51    7.052130
52    6.924901
53    6.680741
54    6.864767
55    7.129217
56    7.178681
57    7.050378
58    6.997824
59    6.929331
Name: stress_level, dtype: float64

In [78]:
rr.pivot_table(index='gender',columns='occupation',values='sleep_quality_score',aggfunc='mean')

occupation,Designer,Doctor,Freelancer,Manager,Researcher,Software Engineer,Student,Teacher
gender,,,,,,,,
Female,6.297439,6.258025,6.315797,6.214964,6.289053,6.247797,6.144879,6.386843
Male,6.341359,6.270889,6.231161,6.196580,6.295119,6.152577,6.092975,6.199285
Other,6.468451,5.986290,6.361806,6.390260,6.336250,6.267356,5.925974,6.423390

In [75]:
rr.pivot_table(index='gender',columns='occupation',values='mental_fatigue_score',aggfunc='mean')

occupation,Designer,Doctor,Freelancer,Manager,Researcher,Software Engineer,Student,Teacher
gender,,,,,,,,
Female,6.753900,6.864801,6.800167,6.999053,6.820605,6.869503,6.998934,6.682423
Male,6.732480,6.854842,6.834707,6.947879,6.796436,6.974635,7.059279,6.949020
Other,6.807606,7.272419,6.620139,6.788312,6.715000,6.896207,7.359610,6.652203

In [73]:
rr.pivot_table(index='gender',columns='occupation',values='sleep_duration_hours',aggfunc='mean')

occupation,Designer,Doctor,Freelancer,Manager,Researcher,Software Engineer,Student,Teacher
gender,,,,,,,,
Female,6.527683,6.391839,6.479911,6.489095,6.552877,6.539276,6.572495,6.483605
Male,6.554700,6.489765,6.494837,6.535595,6.448127,6.460332,6.493227,6.597855
Other,6.574507,6.518387,6.678056,6.753117,6.530000,6.609080,6.527013,6.405085